### ISSUE TITLE
Won't stop switching guns

### ISSUE THREAD

**Issue by Drew12473** [Kalaborative/survivio-plus#138]
HWen I pick up 2 guns, it rapidly switches them until i drop one.

**Comment by minipaik07** [comment]
so do i... it only found at semi auto guns..

**Comment by MisfitRanch101** [comment]
To fix, go to chrome://extensions and disable the extension. then go to Surviv.io and reload the page. Then go back to chrome://extensions and re-enable the extension. Reload Surviv.io and it should be fixed. This happens when you hit your button to switch weapons. You, as I know, can't do that. You must use the number keys to switch weapons

**Comment by MisfitRanch101** [comment]
> To fix, go to chrome://extensions and disable the extension. then go to Surviv.io and reload the page. Then go back to chrome://extensions and re-enable the extension. Reload Surviv.io and it should be fixed. This happens when you hit your button to switch weapons. You, as I know, can't do that. You must use the number keys to switch weapons

also, disabling auto-reload might fix it too

**Comment by survivhacker** [comment]
when you get in the game press esc then change the setting as switch weapons to p so you never have to worry abour it again
