### ISSUE TITLE
Hack doesnt work at all 

### ISSUE THREAD

**Issue by MonsterPlays** [Kalaborative/survivio-plus#17]
Hi, my hack isn't working at all. I re-installed it, but it still wont work. Do more people have this or is this something weird?

Kind regards, 

Monster

**Comment by Kalaborative** [comment]
No it doesn't work at the moment, currently only things working in the game are transparency. 

Due to how the binds work, if I can't figure out how to replace the mouse clicking or key pressing functionality, then there's not really much I can do. 

Custom cursor support and in-game music are available, as well as enemy detection and enemy lines. Sorry for this inconvenience. 

Kindly,
Kalaborative

**Comment by MonsterPlays** [comment]
Hi, first of all no problem. 

Ehm for me transparency isnt working either?

**Comment by Kalaborative** [comment]
sorry that was before my recent commit, transparency should work now

**Comment by humphreygaming** [comment]
so how is the progress going?

**Comment by neeksor** [comment]
These guys seemed to have figured it out. https://github.com/Najlepszy56/Surviv.io-Cheats

**Comment by humphreygaming** [comment]
yeah they did, discovered like 8 hours ago
