### ISSUE TITLE
ISSUE: Not working

### ISSUE THREAD

**Issue by yusefmian** [Kalaborative/survivio-plus#176]
You clearly don't know what you are talking about, friend.  

Below is the freeze bug, that was opened 3 days ago.  The new update was released 1 day ago.  It is a different bug because the entire hack stopped working, but it doesn't freeze the game.  

Please actually take the time to read before closing issues wildly for no reason. It is not necessary and, frankly, it shows lack of detail.

Play surviv.io and you will see.

**Comment by yusefmian** [comment]
This message is for @silentes

**Comment by iNtENSEZZ** [comment]
@Kalaborative Freezing.

**Comment by reflexin** [comment]
He keeps closing the issues because there are duplicate posts. However there is obviously some confusion within this community so perhaps it'd be best to create a master post with all the necessary information. The crashes seem to follow a pattern, usually crashes after a minute or so and on the same line, line 18.
