### ISSUE TITLE
zombs royale

### ISSUE THREAD

**Issue by TesterBoy22** [Kalaborative/survivio-plus#199]
pls make a zombs royale aimbot

**Comment by TesterBoy22** [comment]
I need zomb royale aimbot pls help!

**Comment by survivhacker** [comment]
This is for surviv not zombs

**Comment by TesterBoy22** [comment]
where is zomb royale aimbot then

**Comment by TesterBoy22** [comment]
i need one bad

**Comment by TesterBoy22** [comment]
Dis dude is gay^

**Comment by TesterBoy22** [comment]
I need zomb aimbot

**Comment by survivhacker** [comment]
https://zombsroyaleio.org/

**Comment by survivhacker** [comment]
You don’t download the hack. This is just the information for the game. If you want hacks. Go play the game for a few months on end and your skills will be as worthy as hacks. But still, skills will be much more superior since there is no hacks out there in the public for zombs sadly to those who are trying their best to find one. The developers have thousandths of followers that are waiting for a hack to come out and report it.
