### ISSUE TITLE
plz its literally not working

### ISSUE THREAD

**Issue by slipslipslip** [Kalaborative/survivio-plus#244]
Im not even kidding. I loaded the new extension, and it still doesn't work. The chrome extension gives me the error: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/. and Uncaught TypeError: Cannot read property 'prototype' of undefined. It was working yesterday, but not today.

**Comment by silentes** [comment]
iM NoT EvEn kIdDiNg. I LoAdEd tHe nEw eXtEnSiOn, AnD It sTiLl dOeSn't wOrK. tHe cHrOmE ExTeNsIoN GiVeS Me tHe eRrOr: SyNcHrOnOuS XmLhTtPrEqUeSt oN ThE MaIn tHrEaD Is dEpReCaTeD BeCaUsE Of iTs dEtRiMeNtAl eFfEcTs tO ThE EnD UsEr's eXpErIeNcE. fOr mOrE HeLp, ChEcK HtTpS://XhR.SpEc.wHaTwG.OrG/. AnD UnCaUgHt tYpEeRrOr: CaNnOt rEaD PrOpErTy 'PrOtOtYpE' oF UnDeFiNeD. iT WaS WoRkInG YeStErDaY, bUt nOt tOdAy.

**Comment by silentes** [comment]
Are you retarded. HAVE YOU EVEN TRIED UPDATING THE HACK BEFORE OPENING ISSUES. FUCKING DUMBASS AUTISM CAN BE TREATED IF DIAGNOSED EARLY. STOP OPENING ISSUES AND FUCKING THINK ABOUT WHAT YOU'RE DOING. HOLY SHIT. IF YOU CAN'T GET IT AFTER WATCHING THIS VIDEO, I DON'T KNOW WHAT TO THINK. https://www.youtube.com/watch?v=2iwKaTEeti4&

**Comment by slipslipslip** [comment]
what i did update it lol
