### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by TesterBoy22** [Kalaborative/survivio-plus#316]
Can you fix the aimbot so its more like zbot's he discontinued it and it was better than this aimbot :/

**Comment by mi99cool** [comment]
no its fine as it is, if you migrated from zbot fine use this. See it like this coca cola and Pepsi, Pepsi gets discontinued and you run to coca cola and tell it change the formula to Pepsi they'll be like stfu hell no

**Comment by IceHacks** [comment]
@mi99cool Actually your wrong zbot was continuing a very good one. Way better than `surviv-plus` it never had any mistakes and you could kill people really fast. It also never froze. Also if Pepsi was discontinued nobody would want Coke to change it's recipe 'cause we all know Pepsi sucks. @TesterBoy22 I might fork zbot's and continue it.

**Comment by iBLiSSINYT** [comment]
not really sure what an aimbot that is 'really good' should be. Does it need to play the game for you, or do some people just suck at this game?

**Comment by IceHacks** [comment]
@iBLiSSINYT *"very good". But it just means it would **lock onto players closest to your mouse**, **show the opponents weapons**, a "better" autoloot that **you could change to not pick up weapons**, and some more. They are really amazing features that the users miss but yours is a good updated version of Reukes I suggest at least trying to implement them. No hate meant to be going to you or your work.

**Comment by alexvornoffice** [comment]
I remember choosing a hack between this and powerofunverse's (zbot forked after the account was deleted) and I found that powerofunivers hack was more smoother and better AIM, so the same for zbot, I even worked on improving aim so it will not aim at walls or building if someone is inside... 
But the problem is that people ONLY want someone, no one wants to contribute, like give give give, but nothing in return... If you don't like this cheat - submit a patch and that's all, or create your own custom hack like I do...

**Comment by IceHacks** [comment]
Yeah I have my own private cheats and I was thinking of contributing but I haven't read the code yet.
