### ISSUE TITLE
SUGGESTION.

### ISSUE THREAD

**Issue by RevoltZZ** [Kalaborative/survivio-plus#357]
**I have a suggestion, and I think it might work:
• Disable everything that changes the game in the hack, everything, just leave on the aimbot and the autoloot and bump fire, and try to make it work.**

**Comment by iBLiSSINYT** [comment]
suggestion for what

**Comment by pilgrimoflight** [comment]
Suggestion for that good person that manage the cheat,obviously 
Lets make light version- with only 3 main options. I vote for this too, think it could help with freezing.

**Comment by 1tarko** [comment]
the cheat is not working?

**Comment by TheSatanicAngeI** [comment]
@iBLiSSINYT I agree with what @RevoltZZ  said. It WOULD help a lot to fix the hack. 

A good example of that was the version : https://github.com/yarkoval/survivio-plus/tree/master


but it is now outdated. 

I saw what it was and I assume I froze 1 time on 20 games.

If you could update it with a new fork maybe it would make the hack working better after.

**Comment by iBLiSSINYT** [comment]
what? I do not understand the premise, just disable those options? 

I've been playing with those options ever since it started freezing...

**Comment by TheSatanicAngeI** [comment]
@iBLiSSINYT 

What I'm saying is that yarkoval edit make it look like you don't actually use an hack.

It hides the extension from the extension side bar and all the options like FPS, aiming line, red line for gun, frag grenade timer, delay drop icon, ALL THE OPTIONS that could make you look like you use an hack don't exist anymore on that version.

All you have is the auto aiming when you do RMB and it is very fluent.

The game doesn't lag at all and it doesn't freeze too. 

So maybe you can check it out because even if I disable all the options I still freeze often.

Or can you tell me exactly what to disable ?

**Comment by iBLiSSINYT** [comment]
ok

**Comment by RevoltZZ** [comment]
@iBLiSSINYT Please, make this version, take everything, everything from the beginning of the screen, songs, everything, just leave the autoloot, aimbot and bumpfire, if you do the hack will sure work better!
