### ISSUE TITLE
Use this Extension on Android?

### ISSUE THREAD

**Issue by Calsam12** [Kalaborative/survivio-plus#83]
Hi there this is more of a suggestion than an issue but i was wandering how hard you think this would be to port over to android by making either an app that is just the website and it auto injects the hack before hand (android optimised) or a website that auto injects the hack so no extension is required?

i would like to help out with this (maybe a side branch of the project) if i could

Thanks,
Calsam12

**Comment by Kalaborative** [comment]
as cool as i think that sounds, I have little to no experience in developing Android apps

You could try to auto inject it but it would be a ton of work to essentially recreate the survivio game with the hack embedded, you're basically left with inline JavaScript which is bad for many reasons... and because files aren't loaded asynchronously I'm not even sure that would work anyway

sorry, hopefully someone with more Android experience could help tho
